from .recursive_logit import RecursiveLogitRouteChoice
from .nested_recursive_logit import NestedRecursiveLogitRouteChoice

# Alias for RecursiveLogitRouteChoice
MarkovRouteChoice = RecursiveLogitRouteChoice
